DELETE http://localhost:3001/api/blogs/69148ed4498e2ae0ff08b319
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1YW5hbjM4IiwiaWQiOiI2OTA4ODI3ZWFjMDc2ZjU5ZWZhMzQzNmUiLCJpYXQiOjE3NjI5NTQ5NDB9.8WOumZdVqrx12YLispPnKFLmOB9R32P2Kvp0F1fxOwQ